
name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.6
      with:
        name: tilitin.jar
        path: target/tilitin*.jar
    - name: Upload dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4
    - name: Create Draft Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        release_name: Draft Release ${{ github.ref }}
        draft: true
        prerelease: false
        files: |
          target/tilitin*.jar
